baseURL = "https://www.theautomatedtester.co.uk"
languageCode = "en-us"
title = "David Burns - AutomatedTester"
theme = "hugo-coder"

publishDir = "docs"

googleAnalytics = "UA-1089177-5"

[params]
    author = "David Burns"
    info = "Open Sourcer, Engineer, and Engineering Manager"
    description = "David Burns - Engineer"
    keywords = "blog,developer,personal,selenium,automation,browsers,interoperability"
    avatarurl = "img/David-Burns-Headshot.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "Engineering Effectiveness Nerd"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/automatedtester/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/automatedtester/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/automatedtester/"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
